#!/usr/bin/env python3
"""Build the 144-trace formal extension and a 240-trace combined corpus.

The Pilot corpus is copied only as JSON metadata into the combined authority;
its electrical compact CSV files are never regenerated or modified.  Every
new request has a fresh base waveform ID, and every voltage target is chosen
from the offline VDD-to-slack map rather than from a Vernier sensor code.
"""

from __future__ import print_function

import argparse
import csv
import json
import random
from collections import Counter
from pathlib import Path

from waveform_schema import SAMPLE_COUNT, background_droop_mv, build_trace, event_profile, stable_id


def load_json(path):
    """Load one small declarative configuration or provenance JSON document."""

    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_map(path):
    """Load a strictly monotonic voltage/slack map for bounded inverse lookup."""

    with Path(path).open(newline="", encoding="utf-8") as stream:
        rows = [{"v": float(row["vdd_a_v"]), "s": float(row["worst_slack_ps"])} for row in csv.DictReader(stream)]
    rows.sort(key=lambda row: row["s"])
    if len(rows) < 2 or any(right["s"] <= left["s"] for left, right in zip(rows, rows[1:])):
        raise ValueError("slack map must have strictly increasing slack values for inverse lookup")
    return rows


def voltage_for_slack(points, target_slack_ps):
    """Invert the measured map inside its bounds without extrapolating voltage."""

    target = float(target_slack_ps)
    if target < points[0]["s"] or target > points[-1]["s"]:
        raise ValueError("requested slack {:.6f} ps lies outside calibrated map".format(target))
    for low, high in zip(points, points[1:]):
        if low["s"] <= target <= high["s"]:
            ratio = (target - low["s"]) / (high["s"] - low["s"])
            return low["v"] + ratio * (high["v"] - low["v"])
    return points[-1]["v"]


def make_event(family, duty_cycle, start_index, target_slack_ps, risk_stratum):
    """Describe one event before its amplitude is solved against the slack map."""

    return {"family": family, "amplitude_mv": 0.0, "duty_cycle": float(duty_cycle),
            "length_samples": max(8, int(round(SAMPLE_COUNT * float(duty_cycle)))), "start_index": int(start_index),
            "target_future_min_slack_ps": float(target_slack_ps), "target_risk_stratum": risk_stratum}


def targeted_trace(spec, map_points):
    """Render a trace whose event peak targets a calibrated slack stratum.

    ``build_trace`` owns the final PWL sequence.  This helper repeats its
    deterministic RNG ordering only to calculate the amplitude that will put
    the maximum event sample at the requested offline VDD_A.  The same seed,
    background generator, and profile renderer are then passed back to
    ``build_trace`` so the published sequence is generated by the shared
    schema implementation rather than a second waveform path.
    """

    event = spec["event"]
    rng = random.Random(int(spec["seed"]))
    background = background_droop_mv(spec["background_mode"], rng)
    unit_profile = event_profile(event["family"], 1.0, int(event["length_samples"]), rng)
    peak_offset = max(range(len(unit_profile)), key=lambda index: unit_profile[index])
    peak_scale = unit_profile[peak_offset]
    if peak_scale <= 0.0:
        raise ValueError("event profile has no positive peak")
    target_voltage = voltage_for_slack(map_points, event["target_future_min_slack_ps"])
    target_droop_mv = (1.1 - target_voltage) * 1000.0
    background_at_peak = background[int(event["start_index"]) + peak_offset]
    amplitude = (target_droop_mv - background_at_peak) / peak_scale
    if not 0.2 <= amplitude <= 92.0:
        raise ValueError("targeted event amplitude is outside qualified source range: {:.6f} mV".format(amplitude))
    spec = dict(spec)
    spec["event"] = dict(event, amplitude_mv=round(amplitude, 6), target_peak_vdd_a_v=round(target_voltage, 9))
    return build_trace(spec)


def base_spec(split, ordinal, seed, background_mode, event, ood_axis):
    """Create one independent trace identity before waveform rendering.

    The extension ordinal is included in the base payload intentionally.  The
    formal-dataset objective is more independent base waveforms, not multiple
    random variants accidentally sharing one grouping key.
    """

    base_payload = {"formal_extension_ordinal": int(ordinal), "split": split, "background_mode": background_mode,
                    "family": None if event is None else event["family"], "duty_cycle": None if event is None else event["duty_cycle"],
                    "risk_stratum": None if event is None else event["target_risk_stratum"]}
    base_id = stable_id("base", base_payload)
    trace_id = stable_id("trace", {"base_waveform_id": base_id, "seed": int(seed)})
    return {"schema_version": 2, "trace_id": trace_id, "base_waveform_id": base_id, "split": split, "seed": int(seed),
            "background_mode": background_mode, "waveform_family_id": "background" if event is None else event["family"],
            "event_duty_cycle": None if event is None else event["duty_cycle"], "event": event,
            "source_cohort": "prospective_extension", "ood_axis": ood_axis}


def independent_specs(config, map_points):
    """Build the predeclared 72/24/24 non-pair extension allocation."""

    output = []
    ordinal = 0
    seed_base = int(config["root_seed"])
    known = config["known_families"]
    backgrounds = config["training_background_modes"]
    split_layout = (("train", 12, 60), ("validation", 6, 18), ("iid_test", 6, 18))
    stratum_cycle = (("near_warning", 2.5), ("near_critical", -1.0), ("deep_critical", -6.0))
    for split, normal_count, event_count in split_layout:
        for local_index in range(normal_count + event_count):
            seed = seed_base + ordinal * 7919
            background = backgrounds[ordinal % len(backgrounds)]
            if local_index < normal_count:
                spec = base_spec(split, ordinal, seed, background, None, "iid")
                output.append(build_trace(spec))
            else:
                event_index = local_index - normal_count
                family = known[event_index % len(known)]
                stratum_name, slack = stratum_cycle[event_index % len(stratum_cycle)]
                duty = 0.10 if event_index % 2 == 0 else 0.25
                length = max(8, int(round(SAMPLE_COUNT * duty)))
                start = random.Random(seed ^ 0xB17).randint(24, SAMPLE_COUNT - length - 24)
                event = make_event(family, duty, start, slack, stratum_name)
                spec = base_spec(split, ordinal, seed, background, event, "iid")
                output.append(targeted_trace(spec, map_points))
            ordinal += 1
    return output, ordinal


def hard_pair_values(seed, decision_index, pair_type, critical_droop_mv):
    """Return two 500-frame requests with an identical observable prefix.

    The pair starts from exactly one background realization.  Both target PWL
    arrays are byte-for-byte equal through ``decision_index``; only future
    voltage behavior differs.  HSPICE still decides the actual DFF codes, and
    the full-corpus audit will reject the pair if its measured prefix differs.
    """

    base = background_droop_mv("unseen_multiscale_bursty", random.Random(seed))
    recovering = list(base)
    worsening = list(base)
    duration = {"same_current_code_future_trend": 12, "same_minimum_different_fall_rate": 16,
                "same_amplitude_different_hold": 22, "same_slope_different_future": 14,
                "same_saturation_different_duration": 30}[pair_type]
    for offset in range(1, duration + 1):
        index = decision_index + offset
        if index >= SAMPLE_COUNT:
            break
        progress = float(offset) / float(duration)
        recovering[index] = max(0.2, min(12.0, base[index] + 5.0 * (1.0 - progress)))
        if pair_type == "same_minimum_different_fall_rate":
            worsening[index] = min(99.9, base[index] + critical_droop_mv * progress * progress)
        elif pair_type == "same_amplitude_different_hold":
            worsening[index] = min(99.9, base[index] + critical_droop_mv)
        else:
            worsening[index] = min(99.9, base[index] + critical_droop_mv * progress)
    for index in range(decision_index + duration + 1, SAMPLE_COUNT):
        recovering[index] = min(12.0, base[index])
        worsening[index] = min(99.9, base[index] + critical_droop_mv)
    return [round(value, 9) for value in recovering], [round(value, 9) for value in worsening]


def ood_specs(config, map_points, ordinal):
    """Build 24 OOD rows: 8 typed pairs, 4 safe backgrounds, 4 non-pair events."""

    output = []
    seed_base = int(config["root_seed"])
    critical_droop = (1.1 - voltage_for_slack(map_points, -6.0)) * 1000.0
    pair_types = [name for name, count in config["hard_pair_type_counts"].items() for _ in range(int(count))]
    for pair_number, pair_type in enumerate(pair_types):
        pair_id = "formal_hard_pair_{:02d}".format(pair_number)
        seed = seed_base + (ordinal + pair_number * 2) * 7919
        decision = 80 + (pair_number * 43) % 280
        left_values, right_values = hard_pair_values(seed, decision, pair_type, critical_droop)
        for member, values, future_role in (("recovering", left_values, "recovering"), ("worsening", right_values, "worsening")):
            event = {"family": "hard_pair_{}".format(pair_type), "amplitude_mv": round(critical_droop, 6),
                     "duty_cycle": 0.05 if pair_number % 2 else 0.01, "length_samples": 25 if pair_number % 2 else 8,
                     "start_index": decision, "target_future_min_slack_ps": 2.5 if future_role == "recovering" else -6.0,
                     "target_risk_stratum": "hard_pair", "future_role": future_role}
            spec = base_spec("ood_test", ordinal, seed + (0 if member == "recovering" else 1), "unseen_multiscale_bursty", event, "combined")
            spec.update({"hard_pair_id": pair_id, "hard_pair_type": pair_type, "hard_pair_decision_index": decision,
                         "target_droop_mv": values, "sample_count": SAMPLE_COUNT, "sample_period_s": 4.0e-9})
            output.append(spec)
            ordinal += 1
    for local_index in range(4):
        seed = seed_base + ordinal * 7919
        spec = base_spec("ood_test", ordinal, seed, "unseen_multiscale_bursty", None, "unseen_background")
        output.append(build_trace(spec))
        ordinal += 1
    for local_index in range(4):
        seed = seed_base + ordinal * 7919
        family = config["ood_families"][local_index]
        slack = 2.5 if local_index < 2 else -1.0
        duty = 0.01 if local_index % 2 == 0 else 0.05
        length = max(8, int(round(SAMPLE_COUNT * duty)))
        event = make_event(family, duty, 80 + local_index * 73, slack, "near_warning" if slack > 0 else "near_critical")
        spec = base_spec("ood_test", ordinal, seed, "unseen_multiscale_bursty", event, "combined")
        output.append(targeted_trace(spec, map_points))
        ordinal += 1
    return output


def write_jsonl(path, rows):
    """Write a non-overwriting canonical JSONL corpus with stable key order."""

    if Path(path).exists():
        raise ValueError("refusing to overwrite corpus: {}".format(path))
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with Path(path).open("w", encoding="utf-8") as stream:
        for row in rows:
            stream.write(json.dumps(row, sort_keys=True) + "\n")


def main():
    """Create extension and combined corpus files; HSPICE is not invoked here."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--slack-map", required=True, type=Path)
    parser.add_argument("--legacy-corpus", required=True, type=Path)
    parser.add_argument("--extension-output", required=True, type=Path)
    parser.add_argument("--formal-output", required=True, type=Path)
    args = parser.parse_args()
    config = load_json(args.config)
    map_points = load_map(args.slack_map)
    legacy = [json.loads(line) for line in args.legacy_corpus.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(legacy) != int(config["legacy"]["trace_count"]):
        raise ValueError("legacy corpus count differs from formal configuration")
    legacy_rows = []
    for row in legacy:
        copied = dict(row)
        copied["source_cohort"] = "legacy_pilot"
        copied["ood_axis"] = "legacy_pilot"
        copied.setdefault("hard_pair_type", "legacy_unspecified")
        legacy_rows.append(copied)
    extension, ordinal = independent_specs(config, map_points)
    extension.extend(ood_specs(config, map_points, ordinal))
    expected_extension = sum(int(value) for value in config["extension_split_counts"].values())
    if len(extension) != expected_extension:
        raise ValueError("extension count {} differs from configured {}".format(len(extension), expected_extension))
    counts = Counter(row["split"] for row in extension)
    if dict(sorted(counts.items())) != dict(sorted(config["extension_split_counts"].items())):
        raise ValueError("extension split allocation differs from configuration: {}".format(dict(counts)))
    if len({row["trace_id"] for row in extension}) != len(extension) or len({row["base_waveform_id"] for row in extension}) != len(extension):
        raise ValueError("extension must contain unique trace and base waveform IDs")
    formal = legacy_rows + extension
    formal_counts = Counter(row["split"] for row in formal)
    if dict(sorted(formal_counts.items())) != dict(sorted(config["formal_split_counts"].items())):
        raise ValueError("formal split allocation differs from configuration: {}".format(dict(formal_counts)))
    write_jsonl(args.extension_output, extension)
    write_jsonl(args.formal_output, formal)


if __name__ == "__main__":
    main()
