#!/usr/bin/env python3
"""Run, decode, and electrically validate the direct-chiplet-A timeline.

The sole HSPICE scenario in this runner contains a direct `VDD_A` PWL and the
real standard-cell Vernier/DFF sensor generated by the companion module.  This
program deliberately has no voltage-to-code lookup: each exported code begins
as thirty-two HSPICE-measured DFF Q levels and is then bubble-corrected by the
existing shared thermometer decoder.
"""

import argparse
import bisect
import csv
import hashlib
import json
import math
import re
import subprocess
import sys
from pathlib import Path
from statistics import median
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


REPOSITORY_ROOT = Path(__file__).resolve().parents[4]
PHASE1_SCRIPTS = REPOSITORY_ROOT / "power_macro" / "delay_chain" / "phase1" / "scripts"
SCRIPT_DIR = Path(__file__).resolve().parent
for import_path in (PHASE1_SCRIPTS, SCRIPT_DIR):
    if str(import_path) not in sys.path:
        sys.path.insert(0, str(import_path))
import decode_vernier_code  # noqa: E402  # Sole raw-to-corrected thermometer implementation.
import generate_direct_rail_sensor_timeline_deck as deck_generator  # noqa: E402  # Direct rail deck contract.
import run_dc_sweep  # noqa: E402  # Approved HSPICE/version/listing/MT0 validation.
import run_dff_sweep  # noqa: E402  # Real DFF reset and arrival interpretation.


FIXED_FIELD_WIDTH = 13
TR0_MARKER = "$&%#"
TR0_EXPECTED_LABELS = {
    "time_s": "time",
    "a_vdd_absolute_v": "v(vdd_a",
    "a_vss_absolute_v": "v(vss_a",
    "vdd_ref_absolute_v": "v(vdd_ref",
    "vss_ref_absolute_v": "v(vss_ref",
    "reset_v": "v(sensor_reset",
}

CSV_FIELDS = [
    "scenario_id", "sample_index", "sample_q_read_time_s", "window_index", "direct_droop_window",
    "configured_droop_mv", "configured_vdd_a_v", "a_vdd_v", "measured_droop_mv", "vdd_ref_v",
    "m_stages", "dummy_load_count", "cal_sel", "launch_offset_s", "raw_code", "corrected_code",
    "sensor_code", "raw_bubble_count", "bubble_count", "raw_transition_count", "transition_count",
    "code_valid", "expected_arrival_code", "mismatch_count", "reset_failure_count",
    "metastability_risk_count", "quality",
]


def load_json(path: Path) -> Dict[str, Any]:
    """Load one required JSON object and reject malformed provenance early."""

    with path.open(encoding="utf-8") as stream:
        value = json.load(stream)
    if not isinstance(value, dict):
        raise ValueError("expected JSON object: {}".format(path))
    return value


def sha256_file(path: Path) -> str:
    """Return a streaming digest for one source input or generated deck."""

    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def hspice_executable(config: Dict[str, Any]) -> Tuple[Path, str]:
    """Resolve the Phase-1-approved HSPICE executable and release string."""

    phase1 = load_json(deck_generator.resolve_repo_path(str(config["phase1_config_path"])))
    executable = run_dc_sweep.require_regular_file(Path(phase1["hspice"]), "HSPICE", executable=True)
    version = run_dc_sweep.hspice_version(executable)
    if str(phase1["expected_hspice_version"]) not in version:
        raise RuntimeError("unexpected HSPICE version: {}".format(version))
    return executable, version


def parse_ascii_tr0(path: Path) -> Dict[str, Any]:
    """Parse the fixed-width ASCII `post=2` trace retained by HSPICE.

    HSPICE W-2024.09 prints adjacent 13-character numeric fields without a
    delimiter.  Header labels are 16-character fields and can wrap over lines,
    so this reader restores only those declared field boundaries.  Duplicate
    printed timestamps are retained because field rounding can merge adjacent
    adaptive solver times; a true decrease is rejected.
    """

    if not path.is_file() or path.stat().st_size == 0:
        raise ValueError("HSPICE .tr0 is missing or empty: {}".format(path))
    raw = path.read_text(encoding="ascii", errors="strict")
    width_match = re.match(r"^(\d{4})", raw)
    if width_match is None:
        raise ValueError(".tr0 lacks its four-digit record width")
    record_width = int(width_match.group(1))
    marker_offset = raw.find(TR0_MARKER)
    label_offset = raw.find("TIME")
    if marker_offset < 0 or label_offset < 0 or label_offset >= marker_offset:
        raise ValueError(".tr0 lacks ordered TIME/header marker")
    header = raw[label_offset:marker_offset].replace("\r", "").replace("\n", "")
    if len(header) < record_width * 16:
        raise ValueError(".tr0 label table is shorter than declared record width")
    labels = [header[index * 16:(index + 1) * 16].strip().lower() for index in range(record_width)]
    selected: Dict[str, int] = {}
    for semantic_name, expected_label in TR0_EXPECTED_LABELS.items():
        matches = [index for index, label in enumerate(labels) if label == expected_label]
        if len(matches) != 1:
            raise ValueError(".tr0 requires exactly one {} column; labels={}".format(semantic_name, labels))
        selected[semantic_name] = matches[0]
    if selected["time_s"] != 0:
        raise ValueError(".tr0 TIME must be column zero")
    marker_newline = raw.find("\n", marker_offset)
    if marker_newline < 0:
        raise ValueError(".tr0 marker has no data payload")
    payload = re.sub(r"[\s\r\n]", "", raw[marker_newline + 1:])
    if not payload or len(payload) % FIXED_FIELD_WIDTH:
        raise ValueError(".tr0 payload does not align to fixed numeric fields")
    token_count = len(payload) // FIXED_FIELD_WIDTH
    if token_count % record_width != 1:
        raise ValueError(".tr0 terminal field contract changed")
    record_count = (token_count - 1) // record_width
    columns = {name: [] for name in TR0_EXPECTED_LABELS}
    duplicate_time_count = 0
    previous_time_s = -math.inf
    for record_index in range(record_count):
        record_start = record_index * record_width * FIXED_FIELD_WIDTH
        for semantic_name, column_index in selected.items():
            token_start = record_start + column_index * FIXED_FIELD_WIDTH
            value = float(payload[token_start:token_start + FIXED_FIELD_WIDTH])
            if not math.isfinite(value):
                raise ValueError(".tr0 has non-finite {} at record {}".format(semantic_name, record_index))
            columns[semantic_name].append(value)
        current_time_s = columns["time_s"][-1]
        if record_index == 0 and abs(current_time_s) > 1.0e-18:
            raise ValueError(".tr0 does not begin at time zero")
        if current_time_s < previous_time_s:
            raise ValueError(".tr0 time decreases at record {}".format(record_index))
        if current_time_s == previous_time_s and record_index:
            duplicate_time_count += 1
        previous_time_s = current_time_s
    return {"record_width": record_width, "record_count": record_count, "columns": columns, "duplicate_time_count": duplicate_time_count}


def interpolate_column(trace: Dict[str, Any], name: str, time_s: float) -> float:
    """Evaluate one retained HSPICE PWL quantity at a required measurement time."""

    times = trace["columns"]["time_s"]
    values = trace["columns"][name]
    if time_s < times[0] - 1.0e-18 or time_s > times[-1] + 1.0e-18:
        raise ValueError("query time lies outside .tr0 support")
    right_index = bisect.bisect_right(times, time_s)
    if right_index == 0:
        return values[0]
    left_index = right_index - 1
    if times[left_index] == time_s or right_index == len(times):
        return values[left_index]
    fraction = (time_s - times[left_index]) / (times[right_index] - times[left_index])
    return values[left_index] + fraction * (values[right_index] - values[left_index])


def local_rail(trace: Dict[str, Any], positive_name: str, negative_name: str) -> List[float]:
    """Return a differential rail waveform from two retained absolute probes."""

    return [positive - negative for positive, negative in zip(trace["columns"][positive_name], trace["columns"][negative_name])]


def window_index(study: Dict[str, Any], sample_time_s: float) -> Optional[int]:
    """Return the direct-PWL window containing a capture, or `None` when closed."""

    for index, (start_s, end_s) in enumerate(study["droop_windows_s"]):
        if float(start_s) <= sample_time_s < float(end_s):
            return index
    return None


def quality_for(electrical: Dict[str, Any], decoded: Dict[str, Any]) -> str:
    """Classify a capture without hiding reset, thermometer, or edge evidence."""

    if int(electrical["reset_failure_count"]):
        return "INVALID_RESET"
    if not bool(decoded["code_valid"]):
        return "INVALID_THERMOMETER"
    if int(electrical["metastability_risk_count"]):
        return "VALID_WITH_EDGE_RISK"
    return "VALID"


def decode_samples(config: Dict[str, Any], study: Dict[str, Any], measurements: Dict[str, Optional[float]], trace: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Build five hundred rows solely from real DFF/reset/crossing measurements."""

    rows: List[Dict[str, Any]] = []
    m_stages = int(study["m_stages"])
    for sample_index in range(int(study["sample_count"])):
        per_capture: Dict[str, Optional[float]] = {}
        for stage_index in range(m_stages):
            # Map the multi-frame measure namespace to the established
            # run_dff_sweep parser namespace.  This does not alter values or
            # calculate bits; it merely lets the established reset/aperture
            # implementation inspect the actual HSPICE measurements.
            per_capture["sense_{:03d}_cross".format(stage_index)] = measurements.get("sense_{:03d}_cross_{:03d}".format(sample_index, stage_index))
            per_capture["ref_{:03d}_cross".format(stage_index)] = measurements.get("ref_{:03d}_cross_{:03d}".format(sample_index, stage_index))
            per_capture["q_{:03d}_reset_level".format(stage_index)] = measurements.get("q_{:03d}_reset_level_{:03d}".format(sample_index, stage_index))
            per_capture["q_{:03d}_level".format(stage_index)] = measurements.get("q_{:03d}_level_{:03d}".format(sample_index, stage_index))
        missing = [name for name, value in per_capture.items() if value is None]
        if missing:
            raise ValueError("frame {} is missing DFF evidence: {}".format(sample_index, missing[:4]))
        electrical = run_dff_sweep.parse_bits(
            per_capture,
            m_stages,
            float(config["vdd_ref_v"]),
            float(study["sense_launch_offset_s"]),
            float(config["measurement_timing"]["dff_metastability_margin_s"]),
        )
        decoded = decode_vernier_code.decode_word(str(electrical["raw_code"]))
        sample_time_s = sample_index * float(study["sample_period_s"]) + float(study["sample_q_read_offset_s"])
        measured_a_vdd = measurements.get("sample_{:03d}_a_vdd".format(sample_index))
        measured_ref_vdd = measurements.get("sample_{:03d}_vdd_ref".format(sample_index))
        if measured_a_vdd is None or measured_ref_vdd is None:
            raise ValueError("frame {} lacks rail measurement".format(sample_index))
        trace_a_vdd = interpolate_column(trace, "a_vdd_absolute_v", sample_time_s) - interpolate_column(trace, "a_vss_absolute_v", sample_time_s)
        trace_ref_vdd = interpolate_column(trace, "vdd_ref_absolute_v", sample_time_s) - interpolate_column(trace, "vss_ref_absolute_v", sample_time_s)
        if abs(trace_a_vdd - float(measured_a_vdd)) > 2.0e-4 or abs(trace_ref_vdd - float(measured_ref_vdd)) > 2.0e-4:
            raise ValueError("frame {} .tr0/measure rail disagreement".format(sample_index))
        target_v = deck_generator.frame_target_voltage_v(config, study, sample_index)
        current_window = window_index(study, sample_time_s)
        row = {
            "scenario_id": "direct_rail_timeline",
            "sample_index": sample_index,
            "sample_q_read_time_s": sample_time_s,
            "window_index": "" if current_window is None else current_window,
            "direct_droop_window": current_window is not None,
            "configured_droop_mv": deck_generator.capture_droop_mv(study, sample_index),
            "configured_vdd_a_v": target_v,
            "a_vdd_v": float(measured_a_vdd),
            "measured_droop_mv": (float(config["vnom_v"]) - float(measured_a_vdd)) * 1.0e3,
            "vdd_ref_v": float(measured_ref_vdd),
            "m_stages": m_stages,
            "dummy_load_count": int(study["dummy_load_count"]),
            "cal_sel": int(study["cal_sel"]),
            "launch_offset_s": float(study["sense_launch_offset_s"]),
            "expected_arrival_code": electrical["expected_arrival_code"],
            "mismatch_count": electrical["mismatch_count"],
            "reset_failure_count": electrical["reset_failure_count"],
            "metastability_risk_count": electrical["metastability_risk_count"],
        }
        row.update(decoded)
        row["quality"] = quality_for(electrical, decoded)
        rows.append(row)
    return rows


def valid_rows(rows: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Return reset-correct, thermometer-valid captures while retaining all rows elsewhere."""

    return [row for row in rows if row["quality"] in ("VALID", "VALID_WITH_EDGE_RISK")]


def acceptance_summary(config: Dict[str, Any], study: Dict[str, Any], rows: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    """Apply every approved direct-rail gate to complete, unmodified capture rows.

    Window population is derived from the configured capture clock rather than
    hard-coded from the retired five-frame experiment.  That keeps the
    acceptance contract correct when a window contains many real DFF reads and
    ensures that a truncated HSPICE result cannot pass by merely containing one
    valid high-droop code per window.
    """

    if len(rows) != int(study["sample_count"]):
        raise ValueError("expected {} capture rows, found {}".format(study["sample_count"], len(rows)))
    accepted = valid_rows(rows)
    closed = [row for row in rows if not bool(row["direct_droop_window"])]
    closed_valid = valid_rows(closed)
    if not closed_valid:
        raise ValueError("no valid closed-window captures exist for baseline")
    baseline_code = int(round(float(median([int(row["sensor_code"]) for row in closed_valid]))))
    acceptance = study["acceptance"]
    maximum_closed_delta = int(acceptance["maximum_closed_code_delta_from_baseline"])
    window_minimum = int(acceptance["minimum_window_code_delta_from_baseline"])
    voltage_tolerance = float(acceptance["capture_voltage_tolerance_v"])
    window_details = []
    for index, (start_s, end_s) in enumerate(study["droop_windows_s"]):
        in_window = [row for row in rows if float(start_s) <= float(row["sample_q_read_time_s"]) < float(end_s)]
        valid_in_window = valid_rows(in_window)
        detections = [row for row in valid_in_window if int(row["sensor_code"]) >= baseline_code + window_minimum]
        expected_sample_count = sum(
            float(start_s) <= sample_index * float(study["sample_period_s"]) + float(study["sample_q_read_offset_s"]) < float(end_s)
            for sample_index in range(int(study["sample_count"]))
        )
        configured_droops = [float(row["configured_droop_mv"]) for row in in_window]
        window_details.append({
            "window_index": index, "start_s": float(start_s), "end_s": float(end_s),
            "sample_count": len(in_window), "valid_sample_count": len(valid_in_window),
            "expected_sample_count": expected_sample_count,
            "codes": [int(row["sensor_code"]) for row in valid_in_window], "detection_count": len(detections),
            "configured_droop_unique_count": len(set(configured_droops)),
            "pass": len(in_window) == expected_sample_count and len(valid_in_window) == expected_sample_count and bool(detections),
        })
    voltage_errors = [abs(float(row["a_vdd_v"]) - float(row["configured_vdd_a_v"])) for row in rows]
    invalid = [int(row["sample_index"]) for row in rows if not bool(row["code_valid"])]
    resets = [int(row["sample_index"]) for row in rows if int(row["reset_failure_count"]) != 0]
    window_codes = sorted({int(row["sensor_code"]) for row in valid_rows([row for row in rows if bool(row["direct_droop_window"])])})
    gates = {
        "expected_baseline_code": baseline_code == int(acceptance["expected_baseline_code"]),
        "closed_codes_within_baseline_plus_minus_one": len(closed_valid) == len(closed) and all(abs(int(row["sensor_code"]) - baseline_code) <= maximum_closed_delta for row in closed_valid),
        "all_windows_detected": all(item["pass"] for item in window_details),
        "minimum_distinct_window_codes": len(window_codes) >= int(acceptance["minimum_distinct_window_codes"]),
        "all_windows_have_nonconstant_target_droop": all(item["configured_droop_unique_count"] > 1 for item in window_details),
        "all_codes_valid": not invalid,
        "all_resets_pass": not resets,
        "capture_voltage_matches_direct_pwl": max(voltage_errors) <= voltage_tolerance,
    }
    return {
        "status": "PASS" if all(gates.values()) else "FAIL", "baseline_code": baseline_code,
        "closed_sample_count": len(closed), "closed_valid_sample_count": len(closed_valid),
        "window_details": window_details, "distinct_valid_window_codes": window_codes,
        "distinct_valid_window_code_count": len(window_codes), "invalid_sample_indices": invalid,
        "reset_failure_sample_indices": resets, "maximum_capture_voltage_error_v": max(voltage_errors),
        "gates": gates,
    }


def render_csv_value(value: Any) -> str:
    """Render finite numeric evidence consistently without replacing blanks by zero."""

    if value is None:
        return ""
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("refusing to write non-finite CSV value")
        return "{:.12e}".format(value)
    return str(value)


def write_csv(path: Path, rows: Sequence[Dict[str, Any]]) -> None:
    """Write the complete five-hundred-capture evidence table consumed by plotting."""

    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=CSV_FIELDS, extrasaction="raise")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: render_csv_value(row.get(field)) for field in CSV_FIELDS})


def build_manifest(config_path: Path, config: Dict[str, Any], hspice: Path, version: str, deck_path: Path) -> Dict[str, Any]:
    """Build compact, sufficient provenance for repeatable direct-rail review."""

    return {
        "study_name": "phase2_direct_chiplet_a_rail_sensor_timeline",
        "config_path": str(config_path), "config_sha256": sha256_file(config_path),
        "hspice": {"executable": str(hspice), "version": version},
        "timeline_config": deck_generator.timeline_config(config),
        "deck_path": str(deck_path), "deck_sha256": sha256_file(deck_path),
    }


def run_hspice(hspice: Path, scenario_dir: Path, timeout_s: int) -> None:
    """Execute exactly one task-owned full deck and preserve the command transcript."""

    result = subprocess.run(
        [str(hspice), "direct_rail_sensor.sp", "-o", "direct_rail_sensor"], cwd=str(scenario_dir),
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=False, timeout=timeout_s,
    )
    (scenario_dir / "hspice_command.log").write_text(
        "command={}\nreturncode={}\nstdout:\n{}\nstderr:\n{}\n".format(
            " ".join([str(hspice), "direct_rail_sensor.sp", "-o", "direct_rail_sensor"]), result.returncode, result.stdout, result.stderr
        ), encoding="utf-8"
    )
    if result.returncode != 0:
        raise RuntimeError("HSPICE returned {}".format(result.returncode))


def build_argument_parser() -> argparse.ArgumentParser:
    """Expose a non-overwriting command for one full electrical timeline run."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, type=Path, help="Phase 2 JSON configuration")
    parser.add_argument("--output-dir", required=True, type=Path, help="new task-owned run directory")
    parser.add_argument("--timeout-s", type=int, default=14400, help="full 2 us HSPICE timeout")
    return parser


def main(argv: Optional[Iterable[str]] = None) -> int:
    """Run the direct rail deck, publish all evidence, and return nonzero on FAIL."""

    args = build_argument_parser().parse_args(argv)
    if args.timeout_s <= 0:
        raise ValueError("timeout-s must be positive")
    config_path = args.config.resolve()
    config = load_json(config_path)
    study = deck_generator.timeline_config(config)
    hspice, version = hspice_executable(config)
    output_dir = args.output_dir.resolve()
    if output_dir.exists():
        raise ValueError("refusing to overwrite direct-rail run: {}".format(output_dir))
    scenario_dir = output_dir / "scenario"
    scenario_dir.mkdir(parents=True)
    deck_path = scenario_dir / "direct_rail_sensor.sp"
    deck_generator.write_direct_rail_deck(config, deck_path)
    manifest = build_manifest(config_path, config, hspice, version, deck_path)
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    run_hspice(hspice, scenario_dir, args.timeout_s)
    warning_count = run_dc_sweep.validate_listing(scenario_dir / "direct_rail_sensor.lis")
    measurement_path = run_dc_sweep.find_measurement_file(scenario_dir, "direct_rail_sensor")
    measurements = run_dc_sweep.parse_measurements(measurement_path)
    trace_path = scenario_dir / "direct_rail_sensor.tr0"
    trace = parse_ascii_tr0(trace_path)
    rows = decode_samples(config, study, measurements, trace)
    result = acceptance_summary(config, study, rows)
    result.update({
        "warning_count": warning_count, "measurement_file": str(measurement_path.relative_to(output_dir)),
        "trace_file": str(trace_path.relative_to(output_dir)), "trace_record_count": trace["record_count"],
        "trace_duplicate_time_count": trace["duplicate_time_count"], "a_vdd_min_v": min(local_rail(trace, "a_vdd_absolute_v", "a_vss_absolute_v")),
        "a_vdd_max_v": max(local_rail(trace, "a_vdd_absolute_v", "a_vss_absolute_v")),
    })
    write_csv(output_dir / "direct_rail_samples.csv", rows)
    (output_dir / "timeline_result.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (output_dir / "completion.rpt").write_text(
        "status={}\nsample_count={}\nwarning_count={}\n".format(result["status"], len(rows), warning_count), encoding="ascii"
    )
    return 0 if result["status"] == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
