// ============================================================================
// FTC Phase 9 VCS-XA mixed-signal boundary stub
//
// This module is intentionally NON-SYNTHESIZABLE glue for the VCS-XA flow.
// The `use_spice -cell ftc_sensor_ams` directive replaces this empty digital
// view with the transistor-level `ftc_sensor_ams` subcircuit in the XA deck.
// No calibration behavior is implemented here and no controller signal is
// generated by this stub.
// ============================================================================
module ftc_sensor_ams (
    // Analog sensor result returned to the synthesized controller.  XA drives
    // this port from the Q output of the transistor-level sense DFF.
    output wire       q_final,

    // Controller-owned sensor sampling clock.  The real sensor consumes this
    // signal; the testbench must never drive or alter it.
    input  wire       sense_s_clk,

    // Controller-owned active-high reset for the real sensor DFF.  The real
    // sensor consumes this signal; the testbench must never drive it.
    input  wire       sense_dff_reset,

    // Controller-owned medium thermometer configuration.  Bit 0 is the first
    // medium stage and bit 15 is the last stage in the frozen sensor netlist.
    input  wire [15:0] medium_therm,

    // Controller-owned fine thermometer configuration.  Bit 0 is the first
    // fine stage and bit 9 is the last stage in the frozen sensor netlist.
    input  wire [9:0]  fine_therm,

    // Supply rails are included in the mixed-signal cell boundary so that XA
    // can connect the sensor's transistor-level VDD/VSS pins to the deck.
    input  wire       VDD,
    input  wire       VSS
);
    // The body is empty by design.  XA supplies the implementation selected by
    // vcsAD.init; an RTL assignment here would create a competing Q driver.
endmodule
