###################################################################

# Created by write_sdc on Thu Aug 20 12:05:24 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 16 [current_design]
create_clock [get_ports cal_clk]  -period 1  -waveform {0 0.5}
set_clock_uncertainty 0.05  [get_clocks cal_clk]
set_input_delay -clock cal_clk  -max 0.7  [get_ports cal_start]
set_input_delay -clock cal_clk  -max 0.6  [get_ports q_final]
set_output_delay -clock cal_clk  -max 0.4  [get_ports sense_dff_reset]
set_output_delay -clock cal_clk  -max 0.4  [get_ports sense_s_clk]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[15]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[14]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[13]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[12]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[11]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[10]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[9]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[8]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[7]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[6]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[5]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[4]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[3]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_therm[0]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[9]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[8]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[7]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[6]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[5]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[4]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[3]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_therm[0]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports cal_busy]
set_output_delay -clock cal_clk  -max 0.4  [get_ports cal_done]
set_output_delay -clock cal_clk  -max 0.4  [get_ports cal_fail]
set_output_delay -clock cal_clk  -max 0.4  [get_ports lock_valid]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_code[4]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_code[3]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_code[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_code[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {medium_code[0]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_code[3]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_code[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_code[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fine_code[0]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fail_reason[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fail_reason[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fail_reason[0]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fsm_state[4]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fsm_state[3]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fsm_state[2]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fsm_state[1]}]
set_output_delay -clock cal_clk  -max 0.4  [get_ports {fsm_state[0]}]
set_false_path   -from [get_ports ctrl_por_n]
