// ============================================================================
// FTC sensor ownership handoff
// ============================================================================
// This module is the small, registered control point between the frozen
// startup-calibration controller and a future detection controller.  It lives
// entirely in PD_CTRL.  The outputs of this module are subsequently consumed
// by the already-defined ideal power-aware CTRL-to-SENSE interface.
//
// The implementation deliberately uses no combinational ready-to-mux path:
// det_takeover_ready_i is sampled by the cal_clk_i state machine, and only the
// registered ownership state selects the sensor-control source.  A complete
// H_SWITCH_SAFE clock interval therefore separates calibration ownership from
// detection ownership while reset is asserted and the sensor clock is low.
//
// No Q_FINAL logic is present here.  Q_FINAL remains a direct PD_SENSE to
// PD_CTRL latched-state return into the frozen calibration controller.
// ============================================================================
`timescale 1ns/1ps
`default_nettype none

module ftc_sensor_owner_handoff (
    // ------------------------------------------------------------------------
    // Clock and controller POR
    // ------------------------------------------------------------------------
    // The ownership state machine, snapshot registers, and sticky protocol
    // error all use the same trusted calibration clock as the frozen control
    // path.  ctrl_por_n_i is the only mechanism that can restore CAL ownership.
    input  logic        cal_clk_i,
    input  logic        ctrl_por_n_i,

    // ------------------------------------------------------------------------
    // Frozen startup-calibration status
    // ------------------------------------------------------------------------
    // These signals are generated by ftc_cal_controller_top.  The handoff is
    // allowed to capture a baseline only when all four status conditions and
    // the two safe sensor-control levels are simultaneously true.
    input  logic        cal_busy_i,
    input  logic        cal_done_i,
    input  logic        cal_fail_i,
    input  logic        lock_valid_i,

    // ------------------------------------------------------------------------
    // Frozen calibration-side sensor controls and result codes
    // ------------------------------------------------------------------------
    // The 16-bit medium vector is positive-logic thermometer coding; the
    // 10-bit fine vector is the registered physical vector from the frozen
    // configuration block.  These are sampled as complete buses, not decoded
    // locally, so ownership handoff cannot introduce a new binary decoder or
    // alter the frozen sensor boundary.
    input  logic        cal_sense_dff_reset_i,
    input  logic        cal_sense_s_clk_i,
    input  logic [15:0] cal_medium_therm_i,
    input  logic [9:0]  cal_fine_therm_i,
    input  logic [4:0]  cal_medium_code_i,
    input  logic [3:0]  cal_fine_code_i,

    // ------------------------------------------------------------------------
    // Future detection-side precharge and control interface
    // ------------------------------------------------------------------------
    // det_takeover_ready_i must already be synchronized into cal_clk_i.  H0
    // does not choose a future detector clock.  Before asserting ready, the
    // detector must drive the exact snapshot vectors and the safe levels
    // reset=1 and s_clk=0.  H0 checks those values independently of ready.
    input  logic        det_takeover_ready_i,
    input  logic        det_sense_dff_reset_i,
    input  logic        det_sense_s_clk_i,
    input  logic [15:0] det_medium_therm_i,
    input  logic [9:0]  det_fine_therm_i,

    // ------------------------------------------------------------------------
    // Actual sensor-control outputs
    // ------------------------------------------------------------------------
    // These are the only sensor controls emitted by the H0 wrapper.  During
    // CAL/WAIT they follow the frozen calibration controller, during the
    // one-cycle safe state they are forced to snapshot/reset/low, and after
    // handoff they follow the detection-side controls.
    output logic        sense_dff_reset_o,
    output logic        sense_s_clk_o,
    output logic [15:0] medium_therm_o,
    output logic [9:0]  fine_therm_o,

    // ------------------------------------------------------------------------
    // Immutable calibration baseline outputs
    // ------------------------------------------------------------------------
    // cal_cfg_valid_o becomes true exactly once after a successful calibration
    // and remains true until POR.  The code and thermometer snapshots are
    // read-only to all downstream logic for the rest of that power session.
    output logic        cal_cfg_valid_o,
    output logic [4:0]  cal_medium_code_snapshot_o,
    output logic [3:0]  cal_fine_code_snapshot_o,
    output logic [15:0] cal_medium_therm_snapshot_o,
    output logic [9:0]  cal_fine_therm_snapshot_o,

    // ------------------------------------------------------------------------
    // Ownership handshake and diagnostic outputs
    // ------------------------------------------------------------------------
    // det_prepare_o advertises that a valid snapshot exists and that the
    // detector may precharge its controls.  det_owner_valid_o is asserted only
    // in the registered H_DET_OWNED state.  The two error outputs are sticky
    // until POR so a rejected takeover cannot be mistaken for a transient.
    // handoff_state_o uses the explicit five-state encoding documented in the
    // H0 contract: 0 CAL, 1 WAIT, 2 SAFE, 3 DET, 4 BLOCKED.
    output logic        det_prepare_o,
    output logic        det_owner_valid_o,
    output logic        handoff_blocked_o,
    output logic        handoff_protocol_error_o,
    output logic [2:0]  handoff_state_o
);

    // Explicit state constants make the state encoding part of the reviewable
    // interface contract without requiring a package dependency in this new
    // module.
    localparam logic [2:0] H_CAL_OWNED  = 3'd0;
    localparam logic [2:0] H_WAIT_DET   = 3'd1;
    localparam logic [2:0] H_SWITCH_SAFE = 3'd2;
    localparam logic [2:0] H_DET_OWNED  = 3'd3;
    localparam logic [2:0] H_BLOCKED    = 3'd4;

    logic [2:0] state_q;
    logic [2:0] state_d;
    logic       sensor_cal_enable_q;
    logic       sensor_cal_enable_d;
    logic       sensor_safe_enable_q;
    logic       sensor_safe_enable_d;
    logic       sensor_det_enable_q;
    logic       sensor_det_enable_d;
    logic       sensor_blocked_enable_q;
    logic       sensor_blocked_enable_d;
    logic       cal_cfg_valid_q;
    logic       protocol_error_q;
    logic       blocked_hold_valid_q;

    logic [4:0]  medium_code_snapshot_q;
    logic [3:0]  fine_code_snapshot_q;
    logic [15:0] medium_snapshot_q;
    logic [9:0]  fine_snapshot_q;
    logic [15:0] blocked_medium_q;
    logic [9:0]  blocked_fine_q;

    logic calibration_safe;
    logic detector_precharge_valid;

    // The successful-calibration condition is intentionally explicit.  In
    // particular, cal_done/lock_valid alone are insufficient because a future
    // implementation must not capture a live probe edge or a busy sequencer.
    always_comb begin
        calibration_safe = cal_done_i && lock_valid_i && !cal_fail_i &&
                           !cal_busy_i && cal_sense_dff_reset_i &&
                           !cal_sense_s_clk_i;

        detector_precharge_valid = det_takeover_ready_i &&
                                   (det_medium_therm_i == medium_snapshot_q) &&
                                   (det_fine_therm_i == fine_snapshot_q) &&
                                   det_sense_dff_reset_i &&
                                   !det_sense_s_clk_i;
    end

    // State transitions are purely synchronous at the state-register boundary.
    // No output control signal feeds back into this block, and no clock is
    // gated.  A valid ready is accepted only from H_WAIT_DET; an early or
    // malformed ready is converted into a permanent blocked state.
    always_comb begin
        state_d = state_q;

        case (state_q)
            H_CAL_OWNED: begin
                if (cal_fail_i) begin
                    state_d = H_BLOCKED;
                end else if (calibration_safe) begin
                    state_d = H_WAIT_DET;
                end
            end

            H_WAIT_DET: begin
                if (cal_fail_i) begin
                    state_d = H_BLOCKED;
                end else if (det_takeover_ready_i) begin
                    if (detector_precharge_valid)
                        state_d = H_SWITCH_SAFE;
                    else
                        state_d = H_BLOCKED;
                end
            end

            // This state is deliberately one complete cal_clk interval: the
            // next sequential transition is the only way to reach DET.
            H_SWITCH_SAFE: begin
                state_d = H_DET_OWNED;
            end

            // Detection ownership is one-way for the entire POR session.
            H_DET_OWNED: begin
                state_d = H_DET_OWNED;
            end

            // Both calibration failures and protocol violations stay blocked
            // until POR, with safe sensor outputs selected below.
            H_BLOCKED: begin
                state_d = H_BLOCKED;
            end

            default: begin
                state_d = H_BLOCKED;
            end
        endcase
    end

    // Build registered output enables from the next state.  The normal CAL to
    // SAFE transition changes the selected data from calibration to its exact
    // captured snapshot, so both values are equal at the edge.  On SAFE to DET
    // the safe enable intentionally remains asserted for the first DET cycle;
    // this overlap makes the two already-equal precharged vectors insensitive
    // to cell delay skew.  The following clock removes SAFE before a detector
    // is allowed to change its live controls.
    always_comb begin
        sensor_cal_enable_d     = 1'b0;
        sensor_safe_enable_d    = 1'b0;
        sensor_det_enable_d     = 1'b0;
        sensor_blocked_enable_d = 1'b0;

        case (state_d)
            H_CAL_OWNED,
            H_WAIT_DET: begin
                sensor_cal_enable_d = 1'b1;
            end

            H_SWITCH_SAFE: begin
                sensor_safe_enable_d = 1'b1;
            end

            H_DET_OWNED: begin
                sensor_det_enable_d = 1'b1;
                if (state_q == H_SWITCH_SAFE)
                    sensor_safe_enable_d = 1'b1;
            end

            H_BLOCKED: begin
                sensor_blocked_enable_d = 1'b1;
            end

            default: begin
                sensor_blocked_enable_d = 1'b1;
            end
        endcase
    end

    // State, snapshots, and sticky diagnostics are all clocked together.  The
    // snapshot write is guarded by !cal_cfg_valid_q, making it physically and
    // formally a one-shot capture until the active-low POR is asserted.
    always_ff @(posedge cal_clk_i or negedge ctrl_por_n_i) begin
        if (!ctrl_por_n_i) begin
            state_q                  <= H_CAL_OWNED;
            sensor_cal_enable_q      <= 1'b1;
            sensor_safe_enable_q     <= 1'b0;
            sensor_det_enable_q      <= 1'b0;
            sensor_blocked_enable_q  <= 1'b0;
            cal_cfg_valid_q          <= 1'b0;
            protocol_error_q         <= 1'b0;
            blocked_hold_valid_q     <= 1'b0;
            medium_code_snapshot_q   <= 5'd0;
            fine_code_snapshot_q     <= 4'd0;
            medium_snapshot_q        <= 16'd0;
            fine_snapshot_q          <= 10'd0;
            blocked_medium_q         <= 16'd0;
            blocked_fine_q            <= 10'd0;
        end else begin
            state_q <= state_d;
            sensor_cal_enable_q     <= sensor_cal_enable_d;
            sensor_safe_enable_q    <= sensor_safe_enable_d;
            sensor_det_enable_q     <= sensor_det_enable_d;
            sensor_blocked_enable_q <= sensor_blocked_enable_d;

            if ((state_q == H_CAL_OWNED) && calibration_safe &&
                !cal_cfg_valid_q) begin
                cal_cfg_valid_q        <= 1'b1;
                medium_code_snapshot_q <= cal_medium_code_i;
                fine_code_snapshot_q   <= cal_fine_code_i;
                medium_snapshot_q      <= cal_medium_therm_i;
                fine_snapshot_q        <= cal_fine_therm_i;
            end

            // Capture a stable blocked configuration on the cycle that causes
            // blocking.  A protocol error always has a valid snapshot; a
            // calibration failure may occur before one exists, so its current
            // calibration-side vectors are captured as the final held values.
            if ((state_q == H_CAL_OWNED) && cal_fail_i) begin
                blocked_hold_valid_q <= 1'b1;
                blocked_medium_q     <= cal_medium_therm_i;
                blocked_fine_q        <= cal_fine_therm_i;
            end else if ((state_q == H_WAIT_DET) && cal_fail_i) begin
                blocked_hold_valid_q <= 1'b1;
                blocked_medium_q     <= medium_snapshot_q;
                blocked_fine_q        <= fine_snapshot_q;
            end else if ((state_q == H_WAIT_DET) && det_takeover_ready_i &&
                         !detector_precharge_valid) begin
                blocked_hold_valid_q <= 1'b1;
                blocked_medium_q     <= medium_snapshot_q;
                blocked_fine_q        <= fine_snapshot_q;
                protocol_error_q      <= 1'b1;
            end else if (state_q == H_CAL_OWNED && state_d == H_BLOCKED &&
                         !cal_fail_i) begin
                // Defensive default-state containment; this path does not
                // normally occur, but it prevents an unknown state from
                // releasing an uncontrolled sensor configuration.
                blocked_hold_valid_q <= 1'b1;
                blocked_medium_q     <= cal_medium_therm_i;
                blocked_fine_q        <= cal_fine_therm_i;
            end
        end
    end

    // Outputs are formed from registered, mutually controlled enables.  The
    // AND/OR implementation is deliberately explicit: the safe and detector
    // branches overlap only while their controls are contractually identical,
    // and the safe branch is removed before live detector controls may change.
    // This is a glitch-resistant mux implementation for both clocks and buses,
    // without gating cal_clk_i or creating a combinational feedback path.
    always_comb begin
        sense_dff_reset_o = 1'b0;
        sense_s_clk_o     = 1'b0;
        medium_therm_o    = 16'd0;
        fine_therm_o      = 10'd0;

        if (sensor_cal_enable_q) begin
            sense_dff_reset_o = sense_dff_reset_o | cal_sense_dff_reset_i;
            sense_s_clk_o     = sense_s_clk_o | cal_sense_s_clk_i;
            medium_therm_o    = medium_therm_o | cal_medium_therm_i;
            fine_therm_o      = fine_therm_o | cal_fine_therm_i;
        end
        if (sensor_safe_enable_q) begin
            sense_dff_reset_o = 1'b1;
            sense_s_clk_o     = 1'b0;
            medium_therm_o    = medium_therm_o | medium_snapshot_q;
            fine_therm_o      = fine_therm_o | fine_snapshot_q;
        end
        if (sensor_det_enable_q) begin
            sense_dff_reset_o = sense_dff_reset_o | det_sense_dff_reset_i;
            sense_s_clk_o     = sense_s_clk_o | det_sense_s_clk_i;
            medium_therm_o    = medium_therm_o | det_medium_therm_i;
            fine_therm_o      = fine_therm_o | det_fine_therm_i;
        end
        if (sensor_blocked_enable_q) begin
            sense_dff_reset_o = 1'b1;
            sense_s_clk_o     = 1'b0;
            if (blocked_hold_valid_q) begin
                medium_therm_o = medium_therm_o | blocked_medium_q;
                fine_therm_o   = fine_therm_o | blocked_fine_q;
            end else if (cal_cfg_valid_q) begin
                medium_therm_o = medium_therm_o | medium_snapshot_q;
                fine_therm_o   = fine_therm_o | fine_snapshot_q;
            end
        end
    end

    // Contract outputs are direct views of registered state.  They do not
    // participate in the ownership decision and therefore cannot create a
    // combinational route from detector controls to the sensor mux select.
    always_comb begin
        cal_cfg_valid_o               = cal_cfg_valid_q;
        cal_medium_code_snapshot_o   = medium_code_snapshot_q;
        cal_fine_code_snapshot_o     = fine_code_snapshot_q;
        cal_medium_therm_snapshot_o  = medium_snapshot_q;
        cal_fine_therm_snapshot_o    = fine_snapshot_q;
        det_prepare_o                 = cal_cfg_valid_q && (state_q == H_WAIT_DET);
        det_owner_valid_o             = (state_q == H_DET_OWNED);
        handoff_blocked_o             = (state_q == H_BLOCKED);
        handoff_protocol_error_o      = protocol_error_q;
        handoff_state_o               = state_q;
    end

endmodule

`default_nettype wire
