// ============================================================================
// Phase 9 R3/R4 direct bridge-probe testbench
//
// This bench is intentionally diagnostic-only.  It bypasses the calibration
// FSM and directly selects two frozen M/F anchors so that the XA electrical
// boundary can be compared with the accepted transistor-level probe behavior.
// It must never be used as autonomous Phase 9 acceptance evidence.
//
// The local probe event order is still the canonical Phase 1 schedule:
// reset release at cycle 0, S_CLK rise at cycle 1, sample observations at
// cycles 4 and 5, reset assertion at cycle 6, S_CLK fall at cycle 7, and
// recovery completion at cycle 10.  The testbench records q_final after each
// sample event and counts actual digital S_CLK rising edges independently.
// ============================================================================
`timescale 1ns/1ps

module tb_ftc_vcs_xa_bridge_probe;
    // ------------------------------------------------------------------------
    // Direct diagnostic controls.
    // These are the only signals driven in this isolated bridge experiment.
    // They model the controller output rails at the electrical boundary and
    // are not connected to or substituted for the autonomous FSM.
    // ------------------------------------------------------------------------
    logic sense_s_clk;
    logic sense_dff_reset;
    logic [15:0] medium_therm;
    logic [9:0] fine_therm;

    // ------------------------------------------------------------------------
    // Returned A2D result.
    // q_final is generated by the transistor sensor and converted by the XA
    // bridge.  It is sampled at two post-edge observation points per anchor.
    // ------------------------------------------------------------------------
    logic q_final;

    // ------------------------------------------------------------------------
    // Probe bookkeeping.
    // The counters are event-driven and are included in the compact text
    // evidence consumed by audit_bridge_probe.py.
    // ------------------------------------------------------------------------
    integer sclk_rise_count;
    integer sample1_count;
    integer sample2_count;
    integer recovery_count;
    integer anchor_index;
    logic sample1_q;
    logic sample2_q;
    logic [1:0] anchor_class;

    // Analog voltage samples returned by XA through the supported
    // $snps_get_volt system task.  These values are separate from the digital
    // q_final wire and prove the electrical level seen inside the SPICE cell.
    real analog_q_voltage;
    real analog_sclk_voltage;
    real analog_reset_voltage;
    real analog_vdd_voltage;
    real analog_vss_voltage;

    // Corrected mixed-signal cell.  Its SPICE wrapper owns VDD/VSS internally;
    // no digital supply ports are present on this instance.
    ftc_sensor_ams u_sensor (
        .q_final(q_final),
        .sense_s_clk(sense_s_clk),
        .sense_dff_reset(sense_dff_reset),
        .medium_therm(medium_therm),
        .fine_therm(fine_therm)
    );

    always @(posedge sense_s_clk) begin
        sclk_rise_count = sclk_rise_count + 1;
        if (sense_dff_reset !== 1'b0)
            $display("R4_ERROR anchor=%0d cause=sclk_while_reset", anchor_index);
    end

    // Read the analog-side nodes at a stable observation point.  VDD_LOCAL and
    // VSS_LOCAL are private SPICE nodes created by the corrected wrapper; the
    // hierarchical names are intentionally explicit so a missing probe is not
    // silently converted into a digital estimate.
    task automatic sample_analog_nodes(input string tag);
        begin
            analog_q_voltage = $snps_get_volt(tb_ftc_vcs_xa_bridge_probe.u_sensor.q_final);
            analog_sclk_voltage = $snps_get_volt(tb_ftc_vcs_xa_bridge_probe.u_sensor.sense_s_clk);
            analog_reset_voltage = $snps_get_volt(tb_ftc_vcs_xa_bridge_probe.u_sensor.sense_dff_reset);
            analog_vdd_voltage = $snps_get_volt(tb_ftc_vcs_xa_bridge_probe.u_sensor.VDD_LOCAL);
            analog_vss_voltage = $snps_get_volt(tb_ftc_vcs_xa_bridge_probe.u_sensor.VSS_LOCAL);
            $display("R3_MEASURE tag=%s analog_q=%0.6f analog_sclk=%0.6f analog_reset=%0.6f analog_vdd=%0.6f analog_vss=%0.6f", tag, analog_q_voltage, analog_sclk_voltage, analog_reset_voltage, analog_vdd_voltage, analog_vss_voltage);
        end
    endtask

    // The probe schedule deliberately samples after a small post-clock delay;
    // this avoids using a same-timestep value before the mapped bridge settles.
    task automatic run_anchor(input integer medium_value, input integer fine_value, input string anchor_name);
        integer cycle;
        integer medium_bit;
        integer fine_bit;
        begin
            anchor_index = anchor_index + 1;
            $display("R4_ANCHOR_BEGIN index=%0d name=%s M=%0d F=%0d", anchor_index, anchor_name, medium_value, fine_value);
            medium_therm = 16'b0;
            fine_therm = 10'b1111111111;
            for (medium_bit = 0; medium_bit < medium_value; medium_bit = medium_bit + 1)
                medium_therm[medium_bit] = 1'b1;
            for (fine_bit = 0; fine_bit < fine_value; fine_bit = fine_bit + 1)
                fine_therm[fine_bit] = 1'b0;
            sense_s_clk = 1'b0;
            sense_dff_reset = 1'b1;
            cycle = 0;

            // Cycle 0: reset is released after the configuration is stable.
            #1 sense_dff_reset = 1'b0;
            cycle = 0;
            // Cycle 1: exactly one sensor clock rising edge.
            #1 sense_s_clk = 1'b1;
            // Cycles 2 and 3: hold the clock high while the sensor resolves.
            #2;
            // Cycle 4: first controller-equivalent Q observation.
            #1;
            #0.2 sample1_q = q_final;
            sample_analog_nodes({anchor_name, "_SAMPLE1"});
            sample1_count = sample1_count + 1;
            // Cycle 5: second controller-equivalent Q observation.
            #1;
            #0.2 sample2_q = q_final;
            sample_analog_nodes({anchor_name, "_SAMPLE2"});
            sample2_count = sample2_count + 1;
            // Cycle 6: reassert sensor reset.
            #1 sense_dff_reset = 1'b1;
            // Cycle 7: end the sensor clock pulse.
            #1 sense_s_clk = 1'b0;
            // Cycles 8-10: recovery/quiet interval.
            #3 recovery_count = recovery_count + 1;
            if ((sample1_q === 1'b0) && (sample2_q === 1'b0))
                anchor_class = 2'b00; // stable low
            else if ((sample1_q === 1'b1) && (sample2_q === 1'b1))
                anchor_class = 2'b01; // stable high
            else
                anchor_class = 2'b10; // ambiguous
            $display("R4_ANCHOR_RESULT name=%s M=%0d F=%0d sample1=%b sample2=%b class=%b recovery=1", anchor_name, medium_value, fine_value, sample1_q, sample2_q, anchor_class);
        end
    endtask

    initial begin
        sense_s_clk = 1'b0;
        sense_dff_reset = 1'b1;
        medium_therm = 16'b0;
        fine_therm = 10'b1111111111;
        sclk_rise_count = 0;
        sample1_count = 0;
        sample2_count = 0;
        recovery_count = 0;
        anchor_index = 0;
        sample1_q = 1'bx;
        sample2_q = 1'bx;
        anchor_class = 2'bxx;

        // Allow the analog operating point to settle before the first anchor.
        #5;
        run_anchor(0, 0, "M0_F0");
        #5;
        run_anchor(9, 0, "M9_F0");
        #5;
        if (sclk_rise_count !== 2) $fatal(1, "R4_FAIL cause=sclk_count got=%0d", sclk_rise_count);
        if ((sample1_count !== 2) || (sample2_count !== 2)) $fatal(1, "R4_FAIL cause=sample_count got=%0d/%0d", sample1_count, sample2_count);
        if (recovery_count !== 2) $fatal(1, "R4_FAIL cause=recovery_count got=%0d", recovery_count);
        $display("R4_PASS anchors=2 sclk_edges=2 samples=2/2");
        $finish;
    end

    initial begin
        #100;
        $fatal(1, "R4_FAIL cause=global_timeout");
    end
endmodule
